batch_size: 500
epochs: 30
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BIOSCAN-CLIP-small_experiments
using_train_seen_for_pre_train: true
dataset: bioscan_1m

image:
  input_type: image
  model: lora_vit
  image_encoder_trained_with_simclr_style_ckpt_path: ${project_root_path}/ckpt/uni_model/uni_model/image/image_simclr_style_bioscan_1m/model_best.pth.tar
dna:
  input_type: sequence
  model: lora_barcode_bert
language:
  input_type: sequence
  model: lora_bert

model_output_name: image_dna_text_4gpu_with_pre_trained_image_encoder_trained_with_simclr_style
evaluation_period: 1
ckpt_path: ${project_root_path}/ckpt/bioscan_clip/image_dna_text_4gpu_with_pre_trained_image_encoder_trained_with_simclr_style/2024-11-19_131740/best.pth
output_dim: 768
port: 12355

disable_lora: true
lr_scheduler: one_cycle
lr_config:
  lr: 1e-6
  max_lr: 5e-5

all_gather: true
loss_setup:
  gather_with_grad: true
  use_horovod: false
  local_loss: false
fix_temperature: false
amp: true

random_seed: false

eval_skip_epoch: 23

default_seed: 42

fine_tuning_set:
  batch_size: 150
  epochs: 15
  fine_tune_model_output_dir: ${model_output_dir}/${model_config.model_output_name}/supervise_fine_tune_ckpt